name: Lint and test code
description: Runs linters and tests

inputs:
  interdiscount-coop-user-pw:
    description: Coop user password to access private GitHub npm registry
    required: true
  interdiscount-sonar-token:
    description: Token to access Interdiscount SonarCloud project for the sonar scanner
    required: true
  interdiscount-github-token:
    description: Token of the calling GitHub action for the sonar scannner
    required: true

runs:
  using: composite
  steps:

    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: /opt/sonar-scanner/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: https://npm.pkg.github.com
        scope: '@interdiscount'

    - name: Set timezone to Zurich
      shell: bash
      run: sudo timedatectl set-timezone Europe/Zurich

    - name: Install node packages
      shell: bash
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ inputs.interdiscount-coop-user-pw }}

    - name: Lint CSS
      shell: bash
      run: npm run stylelint

    - name: Lint JavaScript
      shell: bash
      run: npm run lint:ci

    - name: Run unit tests
      shell: bash
      run: npm run test:cover

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ inputs.interdiscount-sonar-token }}
        GITHUB_TOKEN: ${{ inputs.interdiscount-github-token }}